package waf

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// ContentPolicy 上传 / PII 策略（生成 custom 规则，对齐 Imperva 内容检查可配项）。
type ContentPolicy struct {
	UploadMaxBytes int    `json:"upload_max_bytes"`
	UploadExtRx    string `json:"upload_ext_rx"`
	PIIAction      string `json:"pii_action"` // pass | deny
	PIIIDCard      bool   `json:"pii_idcard"`
	PIIMobile      bool   `json:"pii_mobile"`
	PIIBank        bool   `json:"pii_bank"`
}

func DefaultContentPolicy() ContentPolicy {
	return ContentPolicy{
		UploadMaxBytes: 20971520,
		UploadExtRx:    `php\d?|phtml|phar|jsp|asp|aspx|exe|sh|bash|cgi|pl`,
		PIIAction:      "pass",
		PIIIDCard:      true,
		PIIMobile:      true,
		PIIBank:        true,
	}
}

func (m *Manager) contentPolicyPath() string {
	root := filepath.Clean(filepath.Join(m.BackupDir, ".."))
	return filepath.Join(root, "var", "lib", "content_policy.json")
}

func (m *Manager) ReadContentPolicy() (ContentPolicy, error) {
	cfg := DefaultContentPolicy()
	b, err := os.ReadFile(m.contentPolicyPath())
	if err != nil {
		if os.IsNotExist(err) {
			return cfg, nil
		}
		return cfg, err
	}
	if err := json.Unmarshal(b, &cfg); err != nil {
		return DefaultContentPolicy(), err
	}
	if cfg.UploadMaxBytes <= 0 {
		cfg.UploadMaxBytes = 20971520
	}
	if cfg.PIIAction != "deny" {
		cfg.PIIAction = "pass"
	}
	if strings.TrimSpace(cfg.UploadExtRx) == "" {
		cfg.UploadExtRx = DefaultContentPolicy().UploadExtRx
	}
	return cfg, nil
}

func (m *Manager) WriteContentPolicy(cfg ContentPolicy, doReload bool) error {
	if cfg.UploadMaxBytes <= 0 {
		cfg.UploadMaxBytes = 20971520
	}
	if cfg.PIIAction != "deny" {
		cfg.PIIAction = "pass"
	}
	if strings.ContainsAny(cfg.UploadExtRx, `"'\n`) {
		return fmt.Errorf("扩展名正则含非法字符")
	}
	path := m.contentPolicyPath()
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return err
	}
	raw, _ := json.MarshalIndent(cfg, "", "  ")
	if err := os.WriteFile(path, raw, 0o640); err != nil {
		return err
	}
	if err := m.renderUploadRules(cfg); err != nil {
		return err
	}
	if err := m.renderPIIRules(cfg); err != nil {
		return err
	}
	if doReload {
		return m.Reload()
	}
	return nil
}

func (m *Manager) customFile(name string) string {
	return filepath.Join(filepath.Dir(m.ModSecConf), "custom", name)
}

func (m *Manager) renderUploadRules(cfg ContentPolicy) error {
	body := fmt.Sprintf(`# AUTO-GENERATED by ma-waf-api content policy — do not edit
# META: enabled=true; priority=20

SecRule FILES_NAMES "@rx \.(?:%s)$" \
    "id:110001,phase:2,deny,status:403,msg:'Blocked dangerous upload extension',\
    logdata:'%%{MATCHED_VAR}',tag:'attack-upload',tag:'ma-waf-upload',severity:'CRITICAL'"

SecRule FILES_NAMES "@rx \.(?:php|phtml|jsp|asp|aspx)\.[a-z0-9]+$" \
    "id:110002,phase:2,deny,status:403,msg:'Blocked double-extension upload',\
    tag:'attack-upload',tag:'ma-waf-upload',severity:'CRITICAL'"

SecRule FILES "@rx (?i)(?:<\?php|<%%|#!/bin/(?:ba)?sh)" \
    "id:110003,phase:2,deny,status:403,msg:'Blocked malicious upload content',\
    tag:'attack-upload',tag:'ma-waf-upload',severity:'CRITICAL'"

SecRule FILES_SIZES "@gt %d" \
    "id:110004,phase:2,deny,status:403,msg:'Upload file too large',\
    tag:'attack-upload',tag:'ma-waf-upload',severity:'WARNING'
`, cfg.UploadExtRx, cfg.UploadMaxBytes)
	if _, err := m.Backup(); err != nil {
		return err
	}
	return os.WriteFile(m.customFile("110000-upload.conf"), []byte(body), 0o644)
}

func (m *Manager) renderPIIRules(cfg ContentPolicy) error {
	action := "pass,log"
	if cfg.PIIAction == "deny" {
		action = "deny,status:403,auditlog"
	}
	var b strings.Builder
	b.WriteString("# AUTO-GENERATED by ma-waf-api content policy — do not edit\n")
	b.WriteString("# META: enabled=true; priority=20\n\n")
	if cfg.PIIIDCard {
		fmt.Fprintf(&b, `SecRule RESPONSE_BODY "@rx (?<!\d)[1-9]\d{5}(?:19|20)\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\d|3[01])\d{3}[\dXx](?!\d)" \
    "id:110101,phase:4,%s,msg:'Possible ID card leakage in response',\
    tag:'leakage-pii',tag:'ma-waf-pii',severity:'CRITICAL'"

`, action)
	}
	if cfg.PIIMobile {
		fmt.Fprintf(&b, `SecRule RESPONSE_BODY "@rx (?<!\d)1[3-9]\d{9}(?!\d)" \
    "id:110102,phase:4,%s,msg:'Possible mobile number leakage',\
    tag:'leakage-pii',tag:'ma-waf-pii',severity:'WARNING'"

`, action)
	}
	if cfg.PIIBank {
		fmt.Fprintf(&b, `SecRule RESPONSE_BODY "@rx (?<!\d)(?:62|4\d|5[1-5])\d{14,17}(?!\d)" \
    "id:110103,phase:4,%s,msg:'Possible bank card leakage',\
    tag:'leakage-pii',tag:'ma-waf-pii',severity:'CRITICAL'"

`, action)
	}
	if b.Len() < 80 {
		b.WriteString("# all PII checks disabled\n")
	}
	return os.WriteFile(m.customFile("110100-pii.conf"), []byte(b.String()), 0o644)
}
