package waf

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// GenerateOpenAPIRules 生成路径白名单 + 方法矩阵 + JSON Content-Type 基线（Imperva 类 API 防护）。
func (m *Manager) GenerateOpenAPIRules(content []byte, enable, doReload bool) (int, error) {
	var spec map[string]interface{}
	if err := json.Unmarshal(content, &spec); err != nil {
		return 0, fmt.Errorf("仅支持 OpenAPI JSON（请将 YAML 转为 JSON）: %w", err)
	}
	pathsObj, _ := spec["paths"].(map[string]interface{})
	if len(pathsObj) == 0 {
		return 0, fmt.Errorf("spec 无 paths")
	}
	var paths []string
	for p := range pathsObj {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	var alts []string
	var methodRules []string
	rid := 130010
	httpMethods := map[string]bool{
		"get": true, "post": true, "put": true, "patch": true,
		"delete": true, "head": true, "options": true, "trace": true,
	}
	for _, p := range paths {
		rx := normalizeOpenAPIPath(p)
		rx = regexp.MustCompile(`\{[^/]+\}`).ReplaceAllString(rx, `[^/]+`)
		rx = strings.ReplaceAll(rx, `/`, `\/`)
		alts = append(alts, rx)

		item, _ := pathsObj[p].(map[string]interface{})
		var methods []string
		for k := range item {
			lk := strings.ToLower(k)
			if httpMethods[lk] {
				methods = append(methods, strings.ToUpper(lk))
			}
		}
		sort.Strings(methods)
		if len(methods) == 0 {
			continue
		}
		methAlt := strings.Join(methods, "|")
		methodRules = append(methodRules, fmt.Sprintf(`
SecRule REQUEST_URI "@rx ^%s(?:\?.*)?$" \
    "id:%d,phase:1,chain,pass,nolog,auditlog,\
    msg:'API method not allowed for OpenAPI path',\
    tag:'ma-waf/openapi',tag:'ma-waf/api-method',severity:'WARNING'
    SecRule REQUEST_METHOD "!@rx ^(?:%s)$" \
        "t:none"
`, rx, rid, methAlt))
		rid++
		if rid > 130899 {
			break
		}
	}
	joined := strings.Join(alts, "|")
	metaEnabled := "false"
	if enable {
		metaEnabled = "true"
	}
	body := fmt.Sprintf(`# AUTO-GENERATED by ma-waf-api from OpenAPI — review before production
# META: enabled=%s; priority=50; cve=openapi-baseline

# 未知路径（先观察：pass+auditlog；上线可改为 deny）
SecRule REQUEST_URI "!@rx ^(?:%s)(?:\?.*)?$" \
    "id:130001,phase:1,pass,nolog,auditlog,\
    msg:'API path not in OpenAPI allowlist',\
    tag:'ma-waf/openapi',severity:'WARNING'

# 写操作要求 JSON Content-Type
SecRule REQUEST_METHOD "@rx ^(?:POST|PUT|PATCH)$" \
    "id:130002,phase:1,chain,pass,nolog,auditlog,\
    msg:'API write without application/json',\
    tag:'ma-waf/openapi',tag:'ma-waf/api-ct',severity:'WARNING'
    SecRule REQUEST_HEADERS:Content-Type "!@rx (?i)application/json" \
        "t:none"
%s
`, metaEnabled, joined, strings.Join(methodRules, "\n"))

	custom := filepath.Join(filepath.Dir(m.ModSecConf), "custom")
	if err := os.MkdirAll(custom, 0o755); err != nil {
		return 0, err
	}
	_ = os.Remove(filepath.Join(custom, "130000-openapi.conf.off"))
	out := filepath.Join(custom, "130000-openapi.conf")
	if _, err := m.Backup(); err != nil {
		return 0, err
	}
	if err := os.WriteFile(out, []byte(body), 0o644); err != nil {
		return 0, err
	}
	if !enable {
		off := out + ".off"
		_ = os.Remove(off)
		if err := os.Rename(out, off); err != nil {
			return 0, err
		}
	}
	if doReload {
		if err := m.Reload(); err != nil {
			return len(paths), err
		}
	}
	return len(paths), nil
}

func normalizeOpenAPIPath(p string) string {
	p = strings.TrimSpace(p)
	if !strings.HasPrefix(p, "/") {
		p = "/" + p
	}
	p = strings.TrimRight(p, "/")
	if p == "" {
		return "/"
	}
	return p
}
