#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""OpenAPI 规范对比校验（离线）：将请求方法/路径/必需参数与规范比对。

用法:
  python openapi_guard.py validate --spec openapi.yaml --method POST --path /v1/orders --body '{"id":1}'
  python openapi_guard.py gen-rules --spec openapi.yaml --out ../nginx/modsecurity/custom/130000-openapi.conf

说明: 生产环境可在管理面预检或生成 ModSecurity 白名单式规则；完整 JSON Schema
校验建议在 Go API 旁路服务中执行，避免拖慢 Nginx 热路径。
"""
from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys
from typing import Any, Dict, List, Optional, Tuple

try:
    import yaml  # type: ignore
except ImportError:
    yaml = None


def load_spec(path: pathlib.Path) -> Dict[str, Any]:
    text = path.read_text(encoding="utf-8")
    if path.suffix.lower() in {".yaml", ".yml"}:
        if yaml is None:
            raise SystemExit("需要 PyYAML: pip install pyyaml")
        return yaml.safe_load(text)
    return json.loads(text)


def normalize_path(p: str) -> str:
    if not p.startswith("/"):
        p = "/" + p
    return p.rstrip("/") or "/"


def path_to_regex(spec_path: str) -> re.Pattern:
    # /users/{id} -> ^/users/[^/]+$
    parts = []
    for seg in spec_path.strip("/").split("/"):
        if seg.startswith("{") and seg.endswith("}"):
            parts.append(r"[^/]+")
        else:
            parts.append(re.escape(seg))
    return re.compile("^/" + "/".join(parts) + "$")


def find_operation(spec: Dict[str, Any], method: str, path: str) -> Tuple[Optional[str], Optional[Dict]]:
    method = method.lower()
    path = normalize_path(path)
    paths = spec.get("paths") or {}
    for sp, item in paths.items():
        if path_to_regex(normalize_path(sp)).match(path):
            op = (item or {}).get(method)
            if op:
                return sp, op
    return None, None


def cmd_validate(args: argparse.Namespace) -> int:
    spec = load_spec(pathlib.Path(args.spec))
    sp, op = find_operation(spec, args.method, args.path)
    if not op:
        print(json.dumps({"ok": False, "error": "path/method not in OpenAPI", "path": args.path, "method": args.method}))
        return 2
    errors: List[str] = []
    # 必需 query/header/path 参数
    for p in op.get("parameters") or []:
        if not p.get("required"):
            continue
        loc = p.get("in")
        name = p.get("name")
        if loc == "header" and args.header:
            headers = {k.lower(): v for k, v in json.loads(args.header).items()}
            if name.lower() not in headers:
                errors.append(f"missing header: {name}")
        if loc == "query" and args.query:
            q = json.loads(args.query)
            if name not in q:
                errors.append(f"missing query: {name}")
    # 请求体：仅检查 JSON 可解析 + required 字段（若 content 有 schema.required）
    if args.body is not None and args.method.upper() in {"POST", "PUT", "PATCH"}:
        try:
            body = json.loads(args.body) if args.body else {}
        except json.JSONDecodeError:
            errors.append("body is not valid JSON")
            body = {}
        rb = ((op.get("requestBody") or {}).get("content") or {}).get("application/json") or {}
        schema = rb.get("schema") or {}
        for req in schema.get("required") or []:
            if req not in body:
                errors.append(f"missing body field: {req}")
    ok = len(errors) == 0
    print(json.dumps({"ok": ok, "spec_path": sp, "errors": errors}, ensure_ascii=False))
    return 0 if ok else 1


def cmd_gen_rules(args: argparse.Namespace) -> int:
    """生成“仅允许规范中声明的 method+path 前缀”辅助规则（宽松，作第一层）。"""
    spec = load_spec(pathlib.Path(args.spec))
    base = (spec.get("servers") or [{}])[0].get("url", "")
    # 取 path 列表
    paths = sorted((spec.get("paths") or {}).keys())
    methods_by_path: Dict[str, List[str]] = {}
    for p, item in (spec.get("paths") or {}).items():
        methods_by_path[p] = [m.upper() for m in (item or {}).keys() if m in {"get", "post", "put", "patch", "delete", "head", "options"}]

    lines = [
        "# AUTO-GENERATED by openapi_guard.py — review before production",
        "# META: enabled=true; priority=50; cve=openapi-baseline",
        "",
        "# 未知 API 路径：DetectionOnly 建议先观察",
    ]
    # 构造允许的 URI 正则（参数段放宽）
    alts = []
    for p in paths:
        rx = normalize_path(p)
        rx = re.sub(r"\{[^/]+\}", r"[^/]+", rx)
        rx = rx.replace("/", r"\/")
        alts.append(rx)
    if not alts:
        print("spec 无 paths", file=sys.stderr)
        return 1
    joined = "|".join(alts)
    rid = args.rule_id
    lines.append(
        f'SecRule REQUEST_URI "!@rx ^(?:{joined})(?:\\?.*)?$" \\\n'
        f'    "id:{rid},phase:1,pass,nolog,auditlog,\\\n'
        f'    msg:\'API path not in OpenAPI allowlist\',\\\n'
        f'    tag:\'ma-waf/openapi\',severity:\'WARNING\'"'
    )
    lines.append("")
    out = pathlib.Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out} paths={len(paths)} base={base}")
    return 0


def main() -> int:
    p = argparse.ArgumentParser(description="OpenAPI guard for Ma-WAF")
    sub = p.add_subparsers(dest="cmd", required=True)

    v = sub.add_parser("validate")
    v.add_argument("--spec", required=True)
    v.add_argument("--method", required=True)
    v.add_argument("--path", required=True)
    v.add_argument("--body", default=None)
    v.add_argument("--header", default=None, help='JSON object')
    v.add_argument("--query", default=None, help='JSON object')
    v.set_defaults(func=cmd_validate)

    g = sub.add_parser("gen-rules")
    g.add_argument("--spec", required=True)
    g.add_argument("--out", required=True)
    g.add_argument("--rule-id", default="130001")
    g.set_defaults(func=cmd_gen_rules)

    args = p.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
